#
# platform.mak - build target definition
#

#CFLAGS_PLATFORM=-DIBMPC
#NASMFLAGS_PLATFORM=-DIBMPC
#CFLAGS_PLATFORM=-DNEC98 -DJAPAN -DDBCS -DNO_REVISION
CFLAGS_PLATFORM=-DNEC98 -DJAPAN -DDBCS -DNO_REVISION -DALLOW_MBRDISK
NASMFLAGS_PLATFORM=-DNEC98 -DJAPAN -DDBCS

ALLCFLAGS=$(ALLCFLAGS) $(CFLAGS_PLATFORM)
NASMFLAGS=$(NASMFLAGS) $(NASMFLAGS_PLATFORM)
