/* AUTOGENERATED FILE - DO NOT EDIT */
#include "os32_kapi_shared.h"
#include "gfx.h"
#include "palette.h"
#include "kbd.h"
#include "exec_heap.h"
#include "kmalloc.h"
#include "paging.h"
#include "rtc.h"
#include "exec.h"
#include "fm.h"
#include "np2sysp.h"
#include "ide.h"
#include "path.h"
#include "tvram.h"
#include "vfs.h"
#include "ext2.h"
#include "serial.h"
#include "console.h"
#include "dev.h"
#include "kcg.h"
#include "sys.h"
#include "kprintf.h"
#include "io.h"
#include "shm.h"
#include "ime.h"
#include "fd_redirect.h"
#include "pipe_buffer.h"
#include "snd_engine.h"
#include "mouse.h"
#include "kapi_db.h"
#include "loop_dev.h"
#include "v86.h"
#include "gui.h"

extern volatile u32 tick_count;
extern void kapi_sys_exit(int status);
extern void kapi_sys_get_build_info(char *buf, int size);
extern int gfx_stats(void *out);
extern int gfx_lease_palette(int first, int count, const u8 *rgb);

#include "kapi_profile.h"

#ifdef KAPI_PROFILE
volatile u32 kapi_hits[180];
#endif

/* 各スロットの cdecl 引数バイト数 (固定分)。int 0x80 ディスパッチャが
 * ユーザスタックからこの量をコピーして本物の wrap を呼ぶ (可変長は下限)。 */
const u16 kapi_argsize[KAPI_FUNC_COUNT] = {
    0,  /* gfx_init */
    0,  /* gfx_init_200 */
    0,  /* gfx_shutdown */
    0,  /* gfx_present */
    0,  /* kbd_trygetchar */
    4,  /* mem_alloc */
    4,  /* mem_free */
    0,  /* get_tick */
    8,  /* kprintf (...) */
    4,  /* sys_unlink */
    8,  /* sys_rename */
    4,  /* sys_mkdir */
    12,  /* sys_ls */
    0,  /* kmalloc_total */
    0,  /* kmalloc_used */
    0,  /* kmalloc_free */
    0,  /* paging_enabled */
    4,  /* rtc_read */
    0,  /* tvram_clear */
    16,  /* tvram_putchar_at */
    16,  /* tvram_putkanji_at */
    0,  /* tvram_scroll */
    0,  /* kbd_getchar */
    0,  /* kbd_getkey */
    0,  /* kbd_trygetkey */
    12,  /* sys_mount */
    4,  /* sys_umount */
    4,  /* sys_is_mounted */
    4,  /* sys_chdir */
    0,  /* sys_getcwd */
    4,  /* vfs_devname */
    0,  /* vfs_sync */
    4,  /* sys_rmdir */
    4,  /* serial_init */
    4,  /* serial_puts */
    0,  /* serial_getchar */
    4,  /* serial_putchar */
    0,  /* serial_trygetchar */
    0,  /* serial_is_initialized */
    4,  /* exec_run */
    0,  /* dev_count */
    20,  /* dev_get_info */
    0,  /* fm_startup_sound */
    4,  /* fm_play_mml */
    0,  /* np2_detect */
    8,  /* np2_get_version */
    8,  /* np2_get_cpu */
    8,  /* np2_get_clock */
    8,  /* np2_check_hostdrv */
    0,  /* ide_init */
    4,  /* ide_drive_present */
    8,  /* ide_identify */
    12,  /* ide_read_sector */
    0,  /* path_get_drive */
    0,  /* path_get_cwd */
    4,  /* path_set_drive */
    4,  /* path_set_cwd */
    8,  /* path_parse */
    8,  /* ext2_format */
    0,  /* kcg_init */
    4,  /* kcg_set_scale */
    0,  /* buz_on */
    0,  /* buz_off */
    4,  /* rshell_set_active */
    12,  /* ide_write_sector */
    16,  /* ide_write_sectors */
    0,  /* sys_reboot */
    0,  /* sys_halt */
    8,  /* shell_putchar */
    8,  /* shell_print_utf8 */
    0,  /* console_get_cursor_x */
    0,  /* console_get_cursor_y */
    8,  /* console_set_cursor */
    8,  /* sys_open */
    4,  /* sys_close */
    12,  /* sys_read */
    12,  /* sys_write */
    12,  /* sys_lseek */
    8,  /* console_get_size */
    0,  /* kbd_get_modifiers */
    0,  /* sys_get_mem_kb */
    0,  /* sys_time */
    4,  /* gfx_hardware_scroll */
    16,  /* gfx_present_rect */
    4,  /* sys_exit */
    4,  /* sys_isatty */
    8,  /* sys_stat */
    8,  /* sys_fstat */
    16,  /* gfx_set_palette */
    16,  /* gfx_get_palette */
    4,  /* gfx_get_framebuffer */
    16,  /* gfx_add_dirty_rect */
    0,  /* gfx_present_dirty */
    0,  /* gfx_present_nosync */
    4,  /* gfx_present_raster */
    8,  /* kcg_read_ank */
    8,  /* kcg_read_kanji */
    4,  /* sys_shm_alloc */
    4,  /* sys_shm_lock */
    4,  /* sys_shm_free */
    0,  /* ime_getchar */
    0,  /* ime_trygetchar */
    0,  /* ime_toggle */
    0,  /* ime_is_active */
    4,  /* ime_set_mode */
    0,  /* ime_get_mode */
    0,  /* ime_getkey */
    12,  /* sys_redirect_fd */
    4,  /* sys_reset_redirect */
    4,  /* sys_is_redirected */
    0,  /* sys_pipe_alloc */
    4,  /* sys_pipe_free */
    4,  /* sys_pipe_get_buf */
    4,  /* sys_pipe_get_len */
    4,  /* sys_pipe_clear */
    16,  /* sys_redirect_fd_buf */
    4,  /* sys_redirect_get_buf_len */
    4,  /* paging_is_present */
    4,  /* snd_bgm_play */
    0,  /* snd_bgm_stop */
    0,  /* snd_bgm_is_playing */
    4,  /* snd_se_play */
    12,  /* snd_se_play_raw */
    4,  /* snd_set_master */
    4,  /* snd_bgm_set_persist */
    4,  /* kbd_is_pressed */
    8,  /* fm_note_on */
    4,  /* fm_note_off */
    8,  /* fm_set_tone_num */
    8,  /* ssg_tone */
    8,  /* ssg_volume */
    0,  /* ssg_all_off */
    4,  /* mouse_poll */
    0,  /* mouse_available */
    16,  /* mouse_set_bounds */
    16,  /* tvram_readchar_at */
    8,  /* tvram_reverse_cell */
    4,  /* mouse_cursor_set_mode */
    0,  /* mouse_cursor_show */
    0,  /* mouse_cursor_hide */
    4,  /* db_open */
    4,  /* db_close */
    8,  /* db_exec */
    8,  /* db_prepare */
    4,  /* db_step */
    8,  /* db_column_int */
    8,  /* db_column_text */
    4,  /* db_finalize */
    4,  /* db_last_error */
    0,  /* db_mem_used */
    4,  /* kcg_load_font */
    8,  /* ide_get_info */
    8,  /* sys_get_build_info */
    8,  /* loop_attach */
    4,  /* loop_detach */
    12,  /* loop_status */
    16,  /* dev_blk_read */
    16,  /* dev_blk_write */
    4,  /* ime_switch_dict */
    12,  /* ime_user_list */
    8,  /* ime_user_delete */
    4,  /* ime_user_export */
    0,  /* ime_user_clear */
    0,  /* ime_trygetkey */
    0,  /* v86_selftest */
    4,  /* v86_disktest */
    4,  /* v86_boot */
    8,  /* v86_boot2 */
    4,  /* gfx_screen_info */
    20,  /* gfx_hw_fill_rect */
    24,  /* gfx_hw_blit */
    8,  /* gui_call */
    8,  /* gui_register */
    4,  /* gfx_stats */
    12,  /* gfx_lease_palette */
    4,  /* sys_switch_shell */
    0,  /* kbd_dropped_count */
    0,  /* kbd_trygetrawkey */
    4,  /* ime_feed_key */
    4,  /* ime_set_render */
};

/* 各スロットの固定引数のうちポインタ型のビットマスク (bit k = 引数 k)。
 * ディスパッチャが wrap 前に範囲検証する引数を示す (可変長はガード担保)。 */
const u16 kapi_argptr[KAPI_FUNC_COUNT] = {
    0x0000,  /* gfx_init */
    0x0000,  /* gfx_init_200 */
    0x0000,  /* gfx_shutdown */
    0x0000,  /* gfx_present */
    0x0000,  /* kbd_trygetchar */
    0x0000,  /* mem_alloc */
    0x0001,  /* mem_free: ptr */
    0x0000,  /* get_tick */
    0x0002,  /* kprintf: fmt */
    0x0001,  /* sys_unlink: path */
    0x0003,  /* sys_rename: oldpath,newpath */
    0x0001,  /* sys_mkdir: path */
    0x0007,  /* sys_ls: path,cb,ctx */
    0x0000,  /* kmalloc_total */
    0x0000,  /* kmalloc_used */
    0x0000,  /* kmalloc_free */
    0x0000,  /* paging_enabled */
    0x0001,  /* rtc_read: rtc_time */
    0x0000,  /* tvram_clear */
    0x0000,  /* tvram_putchar_at */
    0x0000,  /* tvram_putkanji_at */
    0x0000,  /* tvram_scroll */
    0x0000,  /* kbd_getchar */
    0x0000,  /* kbd_getkey */
    0x0000,  /* kbd_trygetkey */
    0x0007,  /* sys_mount: prefix,dev,fs */
    0x0001,  /* sys_umount: prefix */
    0x0001,  /* sys_is_mounted: prefix */
    0x0001,  /* sys_chdir: path */
    0x0000,  /* sys_getcwd */
    0x0001,  /* vfs_devname: prefix */
    0x0000,  /* vfs_sync */
    0x0001,  /* sys_rmdir: path */
    0x0000,  /* serial_init */
    0x0001,  /* serial_puts: s */
    0x0000,  /* serial_getchar */
    0x0000,  /* serial_putchar */
    0x0000,  /* serial_trygetchar */
    0x0000,  /* serial_is_initialized */
    0x0001,  /* exec_run: path */
    0x0000,  /* dev_count */
    0x001A,  /* dev_get_info: name,type,sects */
    0x0000,  /* fm_startup_sound */
    0x0001,  /* fm_play_mml: mml */
    0x0000,  /* np2_detect */
    0x0001,  /* np2_get_version: buf */
    0x0001,  /* np2_get_cpu: buf */
    0x0001,  /* np2_get_clock: buf */
    0x0001,  /* np2_check_hostdrv: buf */
    0x0000,  /* ide_init */
    0x0000,  /* ide_drive_present */
    0x0002,  /* ide_identify: info */
    0x0004,  /* ide_read_sector: buf */
    0x0000,  /* path_get_drive */
    0x0000,  /* path_get_cwd */
    0x0001,  /* path_set_drive: d */
    0x0001,  /* path_set_cwd: p */
    0x0003,  /* path_parse: input,result */
    0x0000,  /* ext2_format */
    0x0000,  /* kcg_init */
    0x0000,  /* kcg_set_scale */
    0x0000,  /* buz_on */
    0x0000,  /* buz_off */
    0x0000,  /* rshell_set_active */
    0x0004,  /* ide_write_sector: buf */
    0x0008,  /* ide_write_sectors: buf */
    0x0000,  /* sys_reboot */
    0x0000,  /* sys_halt */
    0x0000,  /* shell_putchar */
    0x0001,  /* shell_print_utf8: utf8_str */
    0x0000,  /* console_get_cursor_x */
    0x0000,  /* console_get_cursor_y */
    0x0000,  /* console_set_cursor */
    0x0001,  /* sys_open: path */
    0x0000,  /* sys_close */
    0x0002,  /* sys_read: buf */
    0x0002,  /* sys_write: buf */
    0x0000,  /* sys_lseek */
    0x0003,  /* console_get_size: w,h */
    0x0000,  /* kbd_get_modifiers */
    0x0000,  /* sys_get_mem_kb */
    0x0000,  /* sys_time */
    0x0000,  /* gfx_hardware_scroll */
    0x0000,  /* gfx_present_rect */
    0x0000,  /* sys_exit */
    0x0000,  /* sys_isatty */
    0x0003,  /* sys_stat: path,buf */
    0x0002,  /* sys_fstat: buf */
    0x0000,  /* gfx_set_palette */
    0x000E,  /* gfx_get_palette: r,g,b */
    0x0001,  /* gfx_get_framebuffer: fb */
    0x0000,  /* gfx_add_dirty_rect */
    0x0000,  /* gfx_present_dirty */
    0x0000,  /* gfx_present_nosync */
    0x0001,  /* gfx_present_raster: table */
    0x0002,  /* kcg_read_ank: buf */
    0x0002,  /* kcg_read_kanji: buf */
    0x0000,  /* sys_shm_alloc */
    0x0001,  /* sys_shm_lock: ptr */
    0x0001,  /* sys_shm_free: ptr */
    0x0000,  /* ime_getchar */
    0x0000,  /* ime_trygetchar */
    0x0000,  /* ime_toggle */
    0x0000,  /* ime_is_active */
    0x0000,  /* ime_set_mode */
    0x0000,  /* ime_get_mode */
    0x0000,  /* ime_getkey */
    0x0002,  /* sys_redirect_fd: path */
    0x0000,  /* sys_reset_redirect */
    0x0000,  /* sys_is_redirected */
    0x0000,  /* sys_pipe_alloc */
    0x0000,  /* sys_pipe_free */
    0x0000,  /* sys_pipe_get_buf */
    0x0000,  /* sys_pipe_get_len */
    0x0000,  /* sys_pipe_clear */
    0x0002,  /* sys_redirect_fd_buf: buf */
    0x0000,  /* sys_redirect_get_buf_len */
    0x0000,  /* paging_is_present */
    0x0001,  /* snd_bgm_play: mml */
    0x0000,  /* snd_bgm_stop */
    0x0000,  /* snd_bgm_is_playing */
    0x0000,  /* snd_se_play */
    0x0000,  /* snd_se_play_raw */
    0x0000,  /* snd_set_master */
    0x0000,  /* snd_bgm_set_persist */
    0x0000,  /* kbd_is_pressed */
    0x0000,  /* fm_note_on */
    0x0000,  /* fm_note_off */
    0x0000,  /* fm_set_tone_num */
    0x0000,  /* ssg_tone */
    0x0000,  /* ssg_volume */
    0x0000,  /* ssg_all_off */
    0x0001,  /* mouse_poll: info */
    0x0000,  /* mouse_available */
    0x0000,  /* mouse_set_bounds */
    0x000C,  /* tvram_readchar_at: code,attr */
    0x0000,  /* tvram_reverse_cell */
    0x0000,  /* mouse_cursor_set_mode */
    0x0000,  /* mouse_cursor_show */
    0x0000,  /* mouse_cursor_hide */
    0x0001,  /* db_open: path */
    0x0000,  /* db_close */
    0x0002,  /* db_exec: sql */
    0x0002,  /* db_prepare: sql */
    0x0000,  /* db_step */
    0x0000,  /* db_column_int */
    0x0000,  /* db_column_text */
    0x0000,  /* db_finalize */
    0x0000,  /* db_last_error */
    0x0000,  /* db_mem_used */
    0x0001,  /* kcg_load_font: path */
    0x0002,  /* ide_get_info: info */
    0x0001,  /* sys_get_build_info: buf */
    0x0001,  /* loop_attach: path */
    0x0000,  /* loop_detach */
    0x0006,  /* loop_status: total,bps */
    0x0009,  /* dev_blk_read: dev_name,buf */
    0x0009,  /* dev_blk_write: dev_name,buf */
    0x0000,  /* ime_switch_dict */
    0x0003,  /* ime_user_list: yomi_prefix,out */
    0x0003,  /* ime_user_delete: yomi,kanji */
    0x0001,  /* ime_user_export: path */
    0x0000,  /* ime_user_clear */
    0x0000,  /* ime_trygetkey */
    0x0000,  /* v86_selftest */
    0x0001,  /* v86_disktest: path */
    0x0001,  /* v86_boot: path */
    0x0003,  /* v86_boot2: path,second */
    0x0001,  /* gfx_screen_info: out */
    0x0000,  /* gfx_hw_fill_rect */
    0x0000,  /* gfx_hw_blit */
    0x0000,  /* gui_call */
    0x0003,  /* gui_register: handler,pump */
    0x0001,  /* gfx_stats: out */
    0x0004,  /* gfx_lease_palette: rgb */
    0x0001,  /* sys_switch_shell: path */
    0x0000,  /* kbd_dropped_count */
    0x0000,  /* kbd_trygetrawkey */
    0x0000,  /* ime_feed_key */
    0x0001,  /* ime_set_render: table */
};

void __cdecl wrap_gfx_init(void)
{
    KAPI_HIT(0);
    gfx_init();
}

void __cdecl wrap_gfx_init_200(void)
{
    KAPI_HIT(1);
    gfx_init_200();
}

void __cdecl wrap_gfx_shutdown(void)
{
    KAPI_HIT(2);
    gfx_shutdown();
}

void __cdecl wrap_gfx_present(void)
{
    KAPI_HIT(3);
    gfx_present();
}

int __cdecl wrap_kbd_trygetchar(void)
{
    KAPI_HIT(4);
    return kbd_trygetchar();
}

void * __cdecl wrap_mem_alloc(u32 size)
{
    KAPI_HIT(5);
    return exec_heap_alloc(size);
}

void __cdecl wrap_mem_free(void *ptr)
{
    KAPI_HIT(6);
    exec_heap_free(ptr);
}

u32 __cdecl wrap_get_tick(void)
{
    KAPI_HIT(7);
    return tick_count;
}

int __cdecl wrap_sys_unlink(const char *path)
{
    KAPI_HIT(9);
    return vfs_rm(path);
}

int __cdecl wrap_sys_rename(const char *oldpath, const char *newpath)
{
    KAPI_HIT(10);
    return vfs_rename(oldpath, newpath);
}

int __cdecl wrap_sys_mkdir(const char *path)
{
    KAPI_HIT(11);
    return vfs_mkdir(path);
}

int __cdecl wrap_sys_ls(const char *path, void *cb, void *ctx)
{
    KAPI_HIT(12);
    return vfs_ls(path, (vfs_dir_cb)cb, ctx);
}

u32 __cdecl wrap_kmalloc_total(void)
{
    KAPI_HIT(13);
    return kmalloc_total();
}

u32 __cdecl wrap_kmalloc_used(void)
{
    KAPI_HIT(14);
    return kmalloc_used();
}

u32 __cdecl wrap_kmalloc_free(void)
{
    KAPI_HIT(15);
    return kmalloc_free();
}

int __cdecl wrap_paging_enabled(void)
{
    KAPI_HIT(16);
    return paging_enabled();
}

void __cdecl wrap_rtc_read(void *rtc_time)
{
    KAPI_HIT(17);
    rtc_read((RTC_Time *)rtc_time);
}

void __cdecl wrap_tvram_clear(void)
{
    KAPI_HIT(18);
    tvram_clear();
}

void __cdecl wrap_tvram_putchar_at(int x, int y, char ch, u8 attr)
{
    KAPI_HIT(19);
    tvram_putchar_at(x, y, ch, attr);
}

void __cdecl wrap_tvram_putkanji_at(int x, int y, u16 jis, u8 attr)
{
    KAPI_HIT(20);
    tvram_putkanji_at(x, y, jis, attr);
}

void __cdecl wrap_tvram_scroll(void)
{
    KAPI_HIT(21);
    tvram_scroll();
}

int __cdecl wrap_kbd_getchar(void)
{
    KAPI_HIT(22);
    return kbd_getchar();
}

int __cdecl wrap_kbd_getkey(void)
{
    KAPI_HIT(23);
    return kbd_getkey();
}

int __cdecl wrap_kbd_trygetkey(void)
{
    KAPI_HIT(24);
    return kbd_trygetkey();
}

int __cdecl wrap_sys_mount(const char *prefix, const char *dev, const char *fs)
{
    KAPI_HIT(25);
    return vfs_mount(prefix, dev, fs);
}

void __cdecl wrap_sys_umount(const char *prefix)
{
    KAPI_HIT(26);
    vfs_umount(prefix);
}

int __cdecl wrap_sys_is_mounted(const char *prefix)
{
    KAPI_HIT(27);
    return vfs_is_mounted(prefix);
}

int __cdecl wrap_sys_chdir(const char *path)
{
    KAPI_HIT(28);
    return vfs_chdir(path);
}

const char * __cdecl wrap_sys_getcwd(void)
{
    KAPI_HIT(29);
    return vfs_cwd();
}

const char * __cdecl wrap_vfs_devname(const char *prefix)
{
    KAPI_HIT(30);
    return vfs_devname(prefix);
}

int __cdecl wrap_vfs_sync(void)
{
    KAPI_HIT(31);
    return vfs_sync();
}

int __cdecl wrap_sys_rmdir(const char *path)
{
    KAPI_HIT(32);
    return vfs_rmdir(path);
}

void __cdecl wrap_serial_init(u32 baud)
{
    KAPI_HIT(33);
    serial_init(baud);
}

void __cdecl wrap_serial_puts(const char *s)
{
    KAPI_HIT(34);
    serial_puts(s);
}

int __cdecl wrap_serial_getchar(void)
{
    KAPI_HIT(35);
    return serial_getchar();
}

void __cdecl wrap_serial_putchar(u8 ch)
{
    KAPI_HIT(36);
    serial_putchar(ch);
}

int __cdecl wrap_serial_trygetchar(void)
{
    KAPI_HIT(37);
    return serial_trygetchar();
}

int __cdecl wrap_serial_is_initialized(void)
{
    KAPI_HIT(38);
    return serial_is_initialized();
}

int __cdecl wrap_exec_run(const char *path)
{
    KAPI_HIT(39);
    return exec_run(path);
}

int __cdecl wrap_dev_count(void)
{
    KAPI_HIT(40);
    return dev_count();
}

int __cdecl wrap_dev_get_info(int idx, char *name, int nm, int *type, u32 *sects)
{
    KAPI_HIT(41);
    return dev_api_get_info(idx, name, nm, type, sects);
}

void __cdecl wrap_fm_startup_sound(void)
{
    KAPI_HIT(42);
    fm_startup_sound();
}

void __cdecl wrap_fm_play_mml(const char *mml)
{
    KAPI_HIT(43);
    fm_play_mml(mml);
}

int __cdecl wrap_np2_detect(void)
{
    KAPI_HIT(44);
    return np2_detect();
}

void __cdecl wrap_np2_get_version(char *buf, int size)
{
    KAPI_HIT(45);
    np2_get_version(buf, size);
}

void __cdecl wrap_np2_get_cpu(char *buf, int size)
{
    KAPI_HIT(46);
    np2_get_cpu(buf, size);
}

void __cdecl wrap_np2_get_clock(char *buf, int size)
{
    KAPI_HIT(47);
    np2_get_clock(buf, size);
}

int __cdecl wrap_np2_check_hostdrv(char *buf, int size)
{
    KAPI_HIT(48);
    return np2_check_hostdrv(buf, size);
}

void __cdecl wrap_ide_init(void)
{
    KAPI_HIT(49);
    ide_init();
}

int __cdecl wrap_ide_drive_present(int drv)
{
    KAPI_HIT(50);
    return ide_drive_present(drv);
}

int __cdecl wrap_ide_identify(int drv, void *info)
{
    KAPI_HIT(51);
    return ide_identify(drv, (IdeInfo *)info);
}

int __cdecl wrap_ide_read_sector(int drv, u32 lba, void *buf)
{
    KAPI_HIT(52);
    return ide_read_sector(drv, lba, buf);
}

const char * __cdecl wrap_path_get_drive(void)
{
    KAPI_HIT(53);
    return path_get_drive();
}

const char * __cdecl wrap_path_get_cwd(void)
{
    KAPI_HIT(54);
    return path_get_cwd();
}

int __cdecl wrap_path_set_drive(const char *d)
{
    KAPI_HIT(55);
    return path_set_drive(d);
}

void __cdecl wrap_path_set_cwd(const char *p)
{
    KAPI_HIT(56);
    path_set_cwd(p);
}

void __cdecl wrap_path_parse(const char *input, void *result)
{
    KAPI_HIT(57);
    path_parse(input, (ParsedPath *)result);
}

int __cdecl wrap_ext2_format(int drv, u32 sectors)
{
    KAPI_HIT(58);
    return ext2_format(drv, sectors);
}

void __cdecl wrap_kcg_init(void)
{
    KAPI_HIT(59);
    kcg_init();
}

void __cdecl wrap_kcg_set_scale(int s)
{
    KAPI_HIT(60);
    kcg_set_scale(s);
}

void __cdecl wrap_buz_on(void)
{
    KAPI_HIT(61);
    buz_on();
}

void __cdecl wrap_buz_off(void)
{
    KAPI_HIT(62);
    buz_off();
}

void __cdecl wrap_rshell_set_active(int active)
{
    KAPI_HIT(63);
    rshell_active = active;
}

int __cdecl wrap_ide_write_sector(int drv, u32 lba, const void *buf)
{
    KAPI_HIT(64);
    return ide_write_sector(drv, lba, buf);
}

int __cdecl wrap_ide_write_sectors(int drv, u32 lba, u32 cnt, const void *buf)
{
    KAPI_HIT(65);
    return ide_write_sectors(drv, lba, cnt, buf);
}

void __cdecl wrap_sys_reboot(void)
{
    KAPI_HIT(66);
    sys_reboot();
}

void __cdecl wrap_sys_halt(void)
{
    KAPI_HIT(67);
    sys_halt();
}

void __cdecl wrap_shell_putchar(char ch, u8 attr)
{
    KAPI_HIT(68);
    shell_putchar(ch, attr);
}

void __cdecl wrap_shell_print_utf8(const char *utf8_str, u8 color)
{
    KAPI_HIT(69);
    shell_print_utf8(utf8_str, color);
}

int __cdecl wrap_console_get_cursor_x(void)
{
    KAPI_HIT(70);
    return console_get_cursor_x();
}

int __cdecl wrap_console_get_cursor_y(void)
{
    KAPI_HIT(71);
    return console_get_cursor_y();
}

void __cdecl wrap_console_set_cursor(int x, int y)
{
    KAPI_HIT(72);
    console_set_cursor(x, y);
}

int __cdecl wrap_sys_open(const char *path, int mode)
{
    KAPI_HIT(73);
    return vfs_open(path, mode);
}

void __cdecl wrap_sys_close(int fd)
{
    KAPI_HIT(74);
    vfs_close(fd);
}

int __cdecl wrap_sys_read(int fd, void *buf, u32 size)
{
    KAPI_HIT(75);
    return vfs_read_fd(fd, buf, size);
}

int __cdecl wrap_sys_write(int fd, const void *buf, u32 size)
{
    KAPI_HIT(76);
    return vfs_write_fd(fd, buf, size);
}

int __cdecl wrap_sys_lseek(int fd, int offset, int whence)
{
    KAPI_HIT(77);
    return vfs_seek(fd, offset, whence);
}

void __cdecl wrap_console_get_size(int *w, int *h)
{
    KAPI_HIT(78);
    console_get_size(w, h);
}

u32 __cdecl wrap_kbd_get_modifiers(void)
{
    KAPI_HIT(79);
    return kbd_get_modifiers();
}

u32 __cdecl wrap_sys_get_mem_kb(void)
{
    KAPI_HIT(80);
    return sys_get_mem_kb();
}

os_time_t __cdecl wrap_sys_time(void)
{
    KAPI_HIT(81);
    return sys_time();
}

void __cdecl wrap_gfx_hardware_scroll(int lines)
{
    KAPI_HIT(82);
    gfx_hardware_scroll(lines);
}

void __cdecl wrap_gfx_present_rect(int x, int y, int w, int h)
{
    KAPI_HIT(83);
    gfx_present_rect(x, y, w, h);
}

void __cdecl wrap_sys_exit(int status)
{
    KAPI_HIT(84);
    kapi_sys_exit(status);
}

int __cdecl wrap_sys_isatty(int fd)
{
    KAPI_HIT(85);
    return vfs_isatty(fd);
}

int __cdecl wrap_sys_stat(const char *path, OS32_Stat *buf)
{
    KAPI_HIT(86);
    return vfs_stat(path, buf);
}

int __cdecl wrap_sys_fstat(int fd, OS32_Stat *buf)
{
    KAPI_HIT(87);
    return vfs_fstat(fd, buf);
}

void __cdecl wrap_gfx_set_palette(int idx, u8 r, u8 g, u8 b)
{
    KAPI_HIT(88);
    gfx_set_palette_hal(idx, r, g, b);
}

void __cdecl wrap_gfx_get_palette(int idx, u8 *r, u8 *g, u8 *b)
{
    KAPI_HIT(89);
    palette_get(idx, r, g, b);
}

void __cdecl wrap_gfx_get_framebuffer(void *fb)
{
    KAPI_HIT(90);
    gfx_get_framebuffer(fb);
}

void __cdecl wrap_gfx_add_dirty_rect(int x, int y, int w, int h)
{
    KAPI_HIT(91);
    gfx_add_dirty_rect(x, y, w, h);
}

void __cdecl wrap_gfx_present_dirty(void)
{
    KAPI_HIT(92);
    gfx_present_dirty();
}

void __cdecl wrap_gfx_present_nosync(void)
{
    KAPI_HIT(93);
    gfx_present_nosync();
}

void __cdecl wrap_gfx_present_raster(void *table)
{
    KAPI_HIT(94);
    gfx_present_raster((GFX_RasterPalTable *)table);
}

void __cdecl wrap_kcg_read_ank(u8 ch, u8 *buf)
{
    KAPI_HIT(95);
    kcg_read_ank(ch, buf);
}

void __cdecl wrap_kcg_read_kanji(u16 jis_code, u8 *buf)
{
    KAPI_HIT(96);
    kcg_read_kanji(jis_code, buf);
}

void * __cdecl wrap_sys_shm_alloc(int blocks)
{
    KAPI_HIT(97);
    return shm_alloc(blocks);
}

int __cdecl wrap_sys_shm_lock(void *ptr)
{
    KAPI_HIT(98);
    return shm_lock(ptr);
}

int __cdecl wrap_sys_shm_free(void *ptr)
{
    KAPI_HIT(99);
    return shm_free(ptr);
}

int __cdecl wrap_ime_getchar(void)
{
    KAPI_HIT(100);
    return ime_getchar();
}

int __cdecl wrap_ime_trygetchar(void)
{
    KAPI_HIT(101);
    return ime_trygetchar();
}

void __cdecl wrap_ime_toggle(void)
{
    KAPI_HIT(102);
    ime_toggle();
}

int __cdecl wrap_ime_is_active(void)
{
    KAPI_HIT(103);
    return ime_is_active();
}

void __cdecl wrap_ime_set_mode(int mode)
{
    KAPI_HIT(104);
    ime_set_mode(mode);
}

int __cdecl wrap_ime_get_mode(void)
{
    KAPI_HIT(105);
    return ime_get_mode();
}

int __cdecl wrap_ime_getkey(void)
{
    KAPI_HIT(106);
    return ime_getkey();
}

int __cdecl wrap_sys_redirect_fd(int fd, const char *path, int mode)
{
    KAPI_HIT(107);
    return fd_redirect_to_file(fd, path, mode);
}

void __cdecl wrap_sys_reset_redirect(int fd)
{
    KAPI_HIT(108);
    fd_redirect_reset(fd);
}

int __cdecl wrap_sys_is_redirected(int fd)
{
    KAPI_HIT(109);
    return fd_is_redirected(fd);
}

int __cdecl wrap_sys_pipe_alloc(void)
{
    KAPI_HIT(110);
    return pipe_alloc();
}

void __cdecl wrap_sys_pipe_free(int id)
{
    KAPI_HIT(111);
    pipe_free(id);
}

u8 * __cdecl wrap_sys_pipe_get_buf(int id)
{
    KAPI_HIT(112);
    return pipe_get_buf(id);
}

u32 __cdecl wrap_sys_pipe_get_len(int id)
{
    KAPI_HIT(113);
    return pipe_get_len(id);
}

void __cdecl wrap_sys_pipe_clear(int id)
{
    KAPI_HIT(114);
    pipe_clear(id);
}

int __cdecl wrap_sys_redirect_fd_buf(int fd, u8 *buf, u32 size, u32 len)
{
    KAPI_HIT(115);
    return fd_redirect_to_buffer(fd, buf, size, len);
}

u32 __cdecl wrap_sys_redirect_get_buf_len(int fd)
{
    KAPI_HIT(116);
    return fd_redirect_get_buf_len(fd);
}

int __cdecl wrap_paging_is_present(u32 addr)
{
    KAPI_HIT(117);
    return paging_is_present(addr);
}

void __cdecl wrap_snd_bgm_play(const char *mml)
{
    KAPI_HIT(118);
    snd_bgm_play(mml);
}

void __cdecl wrap_snd_bgm_stop(void)
{
    KAPI_HIT(119);
    snd_bgm_stop();
}

int __cdecl wrap_snd_bgm_is_playing(void)
{
    KAPI_HIT(120);
    return snd_bgm_is_playing();
}

void __cdecl wrap_snd_se_play(int se_id)
{
    KAPI_HIT(121);
    snd_se_play(se_id);
}

void __cdecl wrap_snd_se_play_raw(int note, int duration_ticks, int tone)
{
    KAPI_HIT(122);
    snd_se_play_raw(note, duration_ticks, tone);
}

void __cdecl wrap_snd_set_master(int enable)
{
    KAPI_HIT(123);
    snd_set_master(enable);
}

void __cdecl wrap_snd_bgm_set_persist(int persist)
{
    KAPI_HIT(124);
    snd_bgm_set_persist(persist);
}

int __cdecl wrap_kbd_is_pressed(int scancode)
{
    KAPI_HIT(125);
    return kbd_is_pressed(scancode);
}

void __cdecl wrap_fm_note_on(int ch, int note)
{
    KAPI_HIT(126);
    fm_note_on(ch, note);
}

void __cdecl wrap_fm_note_off(int ch)
{
    KAPI_HIT(127);
    fm_note_off(ch);
}

void __cdecl wrap_fm_set_tone_num(int ch, int tone_num)
{
    KAPI_HIT(128);
    fm_set_tone_num(ch, tone_num);
}

void __cdecl wrap_ssg_tone(int ch, u16 period)
{
    KAPI_HIT(129);
    ssg_tone(ch, period);
}

void __cdecl wrap_ssg_volume(int ch, u8 vol)
{
    KAPI_HIT(130);
    ssg_volume(ch, (uchar)vol);
}

void __cdecl wrap_ssg_all_off(void)
{
    KAPI_HIT(131);
    ssg_all_off();
}

void __cdecl wrap_mouse_poll(void *info)
{
    KAPI_HIT(132);
    mouse_poll((MouseState *)info);
}

int __cdecl wrap_mouse_available(void)
{
    KAPI_HIT(133);
    return mouse_available();
}

void __cdecl wrap_mouse_set_bounds(i16 x_min, i16 y_min, i16 x_max, i16 y_max)
{
    KAPI_HIT(134);
    mouse_set_bounds(x_min, y_min, x_max, y_max);
}

void __cdecl wrap_tvram_readchar_at(int x, int y, u16 *code, u8 *attr)
{
    KAPI_HIT(135);
    tvram_readchar_at(x, y, code, attr);
}

int __cdecl wrap_tvram_reverse_cell(int x, int y)
{
    KAPI_HIT(136);
    return tvram_reverse_cell(x, y);
}

void __cdecl wrap_mouse_cursor_set_mode(int mode)
{
    KAPI_HIT(137);
    mouse_cursor_set_mode(mode);
}

void __cdecl wrap_mouse_cursor_show(void)
{
    KAPI_HIT(138);
    mouse_cursor_show();
}

void __cdecl wrap_mouse_cursor_hide(void)
{
    KAPI_HIT(139);
    mouse_cursor_hide();
}

int __cdecl wrap_db_open(const char *path)
{
    KAPI_HIT(140);
    return kapi_db_open(path);
}

int __cdecl wrap_db_close(int handle)
{
    KAPI_HIT(141);
    return kapi_db_close(handle);
}

int __cdecl wrap_db_exec(int handle, const char *sql)
{
    KAPI_HIT(142);
    return kapi_db_exec(handle, sql);
}

int __cdecl wrap_db_prepare(int handle, const char *sql)
{
    KAPI_HIT(143);
    return kapi_db_prepare(handle, sql);
}

int __cdecl wrap_db_step(int handle)
{
    KAPI_HIT(144);
    return kapi_db_step(handle);
}

int __cdecl wrap_db_column_int(int handle, int col)
{
    KAPI_HIT(145);
    return kapi_db_column_int(handle, col);
}

const char * __cdecl wrap_db_column_text(int handle, int col)
{
    KAPI_HIT(146);
    return kapi_db_column_text(handle, col);
}

int __cdecl wrap_db_finalize(int handle)
{
    KAPI_HIT(147);
    return kapi_db_finalize(handle);
}

const char * __cdecl wrap_db_last_error(int handle)
{
    KAPI_HIT(148);
    return kapi_db_last_error(handle);
}

u32 __cdecl wrap_db_mem_used(void)
{
    KAPI_HIT(149);
    return kapi_db_mem_used();
}

int __cdecl wrap_kcg_load_font(const char *path)
{
    KAPI_HIT(150);
    return kcg_load_font(path);
}

int __cdecl wrap_ide_get_info(int drv, void *info)
{
    KAPI_HIT(151);
    return ide_get_info(drv, (IdeInfo *)info);
}

void __cdecl wrap_sys_get_build_info(char *buf, int size)
{
    KAPI_HIT(152);
    kapi_sys_get_build_info(buf, size);
}

int __cdecl wrap_loop_attach(const char *path, int slot)
{
    KAPI_HIT(153);
    return loop_dev_attach(path, slot);
}

void __cdecl wrap_loop_detach(int slot)
{
    KAPI_HIT(154);
    loop_dev_detach(slot);
}

int __cdecl wrap_loop_status(int slot, u32 *total, int *bps)
{
    KAPI_HIT(155);
    return loop_dev_status(slot, total, bps);
}

int __cdecl wrap_dev_blk_read(const char *dev_name, u32 lba, int count, void *buf)
{
    KAPI_HIT(156);
    { Device *d = dev_find(dev_name); if (!d) return -1; return dev_blk_read_lba(d, lba, count, buf); }
}

int __cdecl wrap_dev_blk_write(const char *dev_name, u32 lba, int count, const void *buf)
{
    KAPI_HIT(157);
    { Device *d = dev_find(dev_name); if (!d) return -1; return dev_blk_write_lba(d, lba, count, buf); }
}

int __cdecl wrap_ime_switch_dict(int variant)
{
    KAPI_HIT(158);
    return ime_switch_dict(variant);
}

int __cdecl wrap_ime_user_list(const char *yomi_prefix, void *out, int max)
{
    KAPI_HIT(159);
    return ime_user_list_facade(yomi_prefix, out, max);
}

int __cdecl wrap_ime_user_delete(const char *yomi, const char *kanji)
{
    KAPI_HIT(160);
    return ime_user_delete_facade(yomi, kanji);
}

int __cdecl wrap_ime_user_export(const char *path)
{
    KAPI_HIT(161);
    return ime_user_export_facade(path);
}

int __cdecl wrap_ime_user_clear(void)
{
    KAPI_HIT(162);
    return ime_user_clear_facade();
}

int __cdecl wrap_ime_trygetkey(void)
{
    KAPI_HIT(163);
    return ime_trygetkey();
}

int __cdecl wrap_v86_selftest(void)
{
    KAPI_HIT(164);
    return v86_smoke_test();
}

int __cdecl wrap_v86_disktest(const char *path)
{
    KAPI_HIT(165);
    return v86_disk_test(path);
}

int __cdecl wrap_v86_boot(const char *path)
{
    KAPI_HIT(166);
    return v86_boot(path);
}

int __cdecl wrap_v86_boot2(const char *path, const char *second)
{
    KAPI_HIT(167);
    return v86_boot2(path, second);
}

void __cdecl wrap_gfx_screen_info(void *out)
{
    KAPI_HIT(168);
    gfx_screen_info(out);
}

int __cdecl wrap_gfx_hw_fill_rect(int x, int y, int w, int h, u8 color)
{
    KAPI_HIT(169);
    return gfx_hw_fill_rect(x, y, w, h, color);
}

int __cdecl wrap_gfx_hw_blit(int dx, int dy, int sx, int sy, int w, int h)
{
    KAPI_HIT(170);
    return gfx_hw_blit(dx, dy, sx, sy, w, h);
}

int __cdecl wrap_gui_call(u32 op, u32 arg)
{
    KAPI_HIT(171);
    return gui_call(op, arg);
}

int __cdecl wrap_gui_register(void *handler, void *pump)
{
    KAPI_HIT(172);
    return gui_register(handler, pump);
}

int __cdecl wrap_gfx_stats(void *out)
{
    KAPI_HIT(173);
    return gfx_stats(out);
}

int __cdecl wrap_gfx_lease_palette(int first, int count, const u8 *rgb)
{
    KAPI_HIT(174);
    return gfx_lease_palette(first, count, rgb);
}

int __cdecl wrap_sys_switch_shell(const char *path)
{
    KAPI_HIT(175);
    return sys_switch_shell(path);
}

u32 __cdecl wrap_kbd_dropped_count(void)
{
    KAPI_HIT(176);
    return kbd_dropped_count();
}

int __cdecl wrap_kbd_trygetrawkey(void)
{
    KAPI_HIT(177);
    return kbd_trygetrawkey();
}

int __cdecl wrap_ime_feed_key(int keydata)
{
    KAPI_HIT(178);
    return ime_feed_key(keydata);
}

void __cdecl wrap_ime_set_render(void *table)
{
    KAPI_HIT(179);
    ime_set_render(table);
}

