/* AUTOGENERATED FILE - DO NOT EDIT */
#include "os32_kapi_shared.h"
#include "gfx.h"
#include "kbd.h"
#include "exec_heap.h"
#include "kmalloc.h"
#include "paging.h"
#include "rtc.h"
#include "exec.h"
#include "fm.h"
#include "np2sysp.h"
#include "ide.h"
#include "path.h"
#include "tvram.h"
#include "vfs.h"
#include "ext2.h"
#include "serial.h"
#include "console.h"
#include "dev.h"
#include "kcg.h"
#include "sys.h"
#include "kprintf.h"
#include "io.h"
#include "lconsole.h"

extern volatile u32 tick_count;
extern void kapi_sys_exit(int status);

void __cdecl wrap_gfx_init(void)
{
    gfx_init();
}

void __cdecl wrap_gfx_shutdown(void)
{
    gfx_shutdown();
}

void __cdecl wrap_gfx_present(void)
{
    gfx_present();
}

void __cdecl wrap_gfx_clear(u8 color)
{
    gfx_clear(color);
}

void __cdecl wrap_gfx_pixel(int x, int y, u8 color)
{
    gfx_pixel(x, y, color);
}

void __cdecl wrap_gfx_hline(int x, int y, int w, u8 color)
{
    gfx_hline(x, y, w, color);
}

void __cdecl wrap_gfx_vline(int x, int y, int h, u8 color)
{
    gfx_vline(x, y, h, color);
}

void __cdecl wrap_gfx_line(int x0, int y0, int x1, int y1, u8 c)
{
    gfx_line(x0, y0, x1, y1, c);
}

void __cdecl wrap_gfx_rect(int x, int y, int w, int h, u8 color)
{
    gfx_rect(x, y, w, h, color);
}

void __cdecl wrap_gfx_fill_rect(int x, int y, int w, int h, u8 c)
{
    gfx_fill_rect(x, y, w, h, c);
}

int __cdecl wrap_kbd_trygetchar(void)
{
    return kbd_trygetchar();
}

void * __cdecl wrap_mem_alloc(u32 size)
{
    return exec_heap_alloc(size);
}

void __cdecl wrap_mem_free(void *ptr)
{
    exec_heap_free(ptr);
}

u32 __cdecl wrap_get_tick(void)
{
    return tick_count;
}

int __cdecl wrap_sys_unlink(const char *path)
{
    return vfs_rm(path);
}

int __cdecl wrap_sys_rename(const char *oldpath, const char *newpath)
{
    return vfs_rename(oldpath, newpath);
}

int __cdecl wrap_sys_mkdir(const char *path)
{
    return vfs_mkdir(path);
}

int __cdecl wrap_sys_ls(const char *path, void *cb, void *ctx)
{
    return vfs_ls(path, (vfs_dir_cb)cb, ctx);
}

u32 __cdecl wrap_kmalloc_total(void)
{
    return kmalloc_total();
}

u32 __cdecl wrap_kmalloc_used(void)
{
    return kmalloc_used();
}

u32 __cdecl wrap_kmalloc_free(void)
{
    return kmalloc_free();
}

int __cdecl wrap_paging_enabled(void)
{
    return paging_enabled();
}

void __cdecl wrap_rtc_read(void *rtc_time)
{
    rtc_read((RTC_Time *)rtc_time);
}

void __cdecl wrap_tvram_clear(void)
{
    tvram_clear();
}

void __cdecl wrap_tvram_putchar_at(int x, int y, char ch, u8 attr)
{
    tvram_putchar_at(x, y, ch, attr);
}

void __cdecl wrap_tvram_putkanji_at(int x, int y, u16 jis, u8 attr)
{
    tvram_putkanji_at(x, y, jis, attr);
}

void __cdecl wrap_tvram_scroll(void)
{
    tvram_scroll();
}

int __cdecl wrap_kbd_getchar(void)
{
    return kbd_getchar();
}

int __cdecl wrap_kbd_getkey(void)
{
    return kbd_getkey();
}

int __cdecl wrap_kbd_trygetkey(void)
{
    return kbd_trygetkey();
}

int __cdecl wrap_sys_mount(const char *prefix, const char *dev, const char *fs)
{
    return vfs_mount(prefix, dev, fs);
}

void __cdecl wrap_sys_umount(const char *prefix)
{
    vfs_umount(prefix);
}

int __cdecl wrap_sys_is_mounted(const char *prefix)
{
    return vfs_is_mounted(prefix);
}

int __cdecl wrap_sys_chdir(const char *path)
{
    return vfs_chdir(path);
}

const char * __cdecl wrap_sys_getcwd(void)
{
    return vfs_cwd();
}

const char * __cdecl wrap_vfs_devname(const char *prefix)
{
    return vfs_devname(prefix);
}

int __cdecl wrap_vfs_sync(void)
{
    return vfs_sync();
}

int __cdecl wrap_sys_rmdir(const char *path)
{
    return vfs_rmdir(path);
}

void __cdecl wrap_serial_init(u32 baud)
{
    serial_init(baud);
}

void __cdecl wrap_serial_puts(const char *s)
{
    serial_puts(s);
}

int __cdecl wrap_serial_getchar(void)
{
    return serial_getchar();
}

void __cdecl wrap_serial_putchar(u8 ch)
{
    serial_putchar(ch);
}

int __cdecl wrap_serial_trygetchar(void)
{
    return serial_trygetchar();
}

int __cdecl wrap_serial_is_initialized(void)
{
    return serial_is_initialized();
}

int __cdecl wrap_exec_run(const char *path)
{
    return exec_run(path);
}

int __cdecl wrap_dev_count(void)
{
    return dev_count();
}

int __cdecl wrap_dev_get_info(int idx, char *name, int nm, int *type, u32 *sects)
{
    return dev_api_get_info(idx, name, nm, type, sects);
}

void __cdecl wrap_fm_startup_sound(void)
{
    fm_startup_sound();
}

void __cdecl wrap_fm_play_mml(const char *mml)
{
    fm_play_mml(mml);
}

int __cdecl wrap_np2_detect(void)
{
    return np2_detect();
}

void __cdecl wrap_np2_get_version(char *buf, int size)
{
    np2_get_version(buf, size);
}

void __cdecl wrap_np2_get_cpu(char *buf, int size)
{
    np2_get_cpu(buf, size);
}

void __cdecl wrap_np2_get_clock(char *buf, int size)
{
    np2_get_clock(buf, size);
}

int __cdecl wrap_np2_check_hostdrv(char *buf, int size)
{
    return np2_check_hostdrv(buf, size);
}

void __cdecl wrap_ide_init(void)
{
    ide_init();
}

int __cdecl wrap_ide_drive_present(int drv)
{
    return ide_drive_present(drv);
}

int __cdecl wrap_ide_identify(int drv, void *info)
{
    return ide_identify(drv, (IdeInfo *)info);
}

int __cdecl wrap_ide_read_sector(int drv, u32 lba, void *buf)
{
    return ide_read_sector(drv, lba, buf);
}

const char * __cdecl wrap_path_get_drive(void)
{
    return path_get_drive();
}

const char * __cdecl wrap_path_get_cwd(void)
{
    return path_get_cwd();
}

int __cdecl wrap_path_set_drive(const char *d)
{
    return path_set_drive(d);
}

void __cdecl wrap_path_set_cwd(const char *p)
{
    path_set_cwd(p);
}

void __cdecl wrap_path_parse(const char *input, void *result)
{
    path_parse(input, (ParsedPath *)result);
}

int __cdecl wrap_ext2_format(int drv, u32 sectors)
{
    return ext2_format(drv, sectors);
}

void __cdecl wrap_kcg_init(void)
{
    kcg_init();
}

void __cdecl wrap_kcg_set_scale(int s)
{
    kcg_set_scale(s);
}

void __cdecl wrap_kcg_draw_ank(int x, int y, u8 ch, u8 fg, u8 bg)
{
    kcg_draw_ank(x, y, ch, fg, bg);
}

void __cdecl wrap_kcg_draw_kanji(int x, int y, u16 jis, u8 fg, u8 bg)
{
    kcg_draw_kanji(x, y, jis, fg, bg);
}

int __cdecl wrap_kcg_draw_utf8(int x, int y, const char *str, u8 fg, u8 bg)
{
    return kcg_draw_utf8(x, y, str, fg, bg);
}

int __cdecl wrap_kcg_draw_sjis(int x, int y, const char *str, u8 fg, u8 bg)
{
    return kcg_draw_sjis(x, y, str, fg, bg);
}

void __cdecl wrap_buz_on(void)
{
    buz_on();
}

void __cdecl wrap_buz_off(void)
{
    buz_off();
}

void __cdecl wrap_rshell_set_active(int active)
{
    rshell_active = active;
}

int __cdecl wrap_ide_write_sector(int drv, u32 lba, const void *buf)
{
    return ide_write_sector(drv, lba, buf);
}

int __cdecl wrap_ide_write_sectors(int drv, u32 lba, u32 cnt, const void *buf)
{
    return ide_write_sectors(drv, lba, cnt, buf);
}

void __cdecl wrap_sys_reboot(void)
{
    sys_reboot();
}

void __cdecl wrap_sys_halt(void)
{
    sys_halt();
}

void __cdecl wrap_shell_putchar(char ch, u8 attr)
{
    shell_putchar(ch, attr);
}

int __cdecl wrap_console_get_cursor_x(void)
{
    return console_get_cursor_x();
}

int __cdecl wrap_console_get_cursor_y(void)
{
    return console_get_cursor_y();
}

void __cdecl wrap_console_set_cursor(int x, int y)
{
    console_set_cursor(x, y);
}

int __cdecl wrap_sys_open(const char *path, int mode)
{
    return vfs_open(path, mode);
}

void __cdecl wrap_sys_close(int fd)
{
    vfs_close(fd);
}

int __cdecl wrap_sys_read(int fd, void *buf, u32 size)
{
    return vfs_read_fd(fd, buf, size);
}

int __cdecl wrap_sys_write(int fd, const void *buf, u32 size)
{
    return vfs_write_fd(fd, buf, size);
}

int __cdecl wrap_sys_lseek(int fd, int offset, int whence)
{
    return vfs_seek(fd, offset, whence);
}

void __cdecl wrap_console_get_size(int *w, int *h)
{
    console_get_size(w, h);
}

u32 __cdecl wrap_kbd_get_modifiers(void)
{
    return kbd_get_modifiers();
}

u32 __cdecl wrap_sys_get_mem_kb(void)
{
    return sys_get_mem_kb();
}

os_time_t __cdecl wrap_sys_time(void)
{
    return sys_time();
}

void __cdecl wrap_gfx_hardware_scroll(int lines)
{
    gfx_hardware_scroll(lines);
}

void __cdecl wrap_gfx_present_rect(int x, int y, int w, int h)
{
    gfx_present_rect(x, y, w, h);
}

void __cdecl wrap_sys_exit(int status)
{
    kapi_sys_exit(status);
}

int __cdecl wrap_sys_isatty(int fd)
{
    return vfs_isatty(fd);
}

int __cdecl wrap_sys_stat(const char *path, OS32_Stat *buf)
{
    return vfs_stat(path, buf);
}

int __cdecl wrap_sys_fstat(int fd, OS32_Stat *buf)
{
    return vfs_fstat(fd, buf);
}

void __cdecl wrap_lcons_clear(void)
{
    lcons_clear();
}

void __cdecl wrap_lcons_putc(int x, int y, char ch, u8 attr)
{
    lcons_putc(x, y, ch, attr);
}

void __cdecl wrap_lcons_putkanji(int x, int y, u16 jis, u8 attr)
{
    lcons_putkanji(x, y, jis, attr);
}

void __cdecl wrap_lcons_fill_rect(int x, int y, int w, int h, char ch, u8 attr)
{
    lcons_fill_rect(x, y, w, h, ch, attr);
}

void __cdecl wrap_lcons_sync_vram(void)
{
    lcons_sync_vram();
}

int __cdecl wrap_gfx_screenshot(const char *path)
{
    return gfx_screenshot(path);
}

int __cdecl wrap_gfx_load_vdp(const char *path)
{
    return gfx_load_vdp(path);
}

