/* AUTOGENERATED FILE - DO NOT EDIT */
#include "os32_kapi_shared.h"
#include "gfx.h"
#include "palette.h"
#include "kbd.h"
#include "exec_heap.h"
#include "kmalloc.h"
#include "paging.h"
#include "rtc.h"
#include "exec.h"
#include "fm.h"
#include "np2sysp.h"
#include "ide.h"
#include "path.h"
#include "tvram.h"
#include "vfs.h"
#include "ext2.h"
#include "serial.h"
#include "console.h"
#include "dev.h"
#include "kcg.h"
#include "sys.h"
#include "kprintf.h"
#include "io.h"
#include "shm.h"
#include "ime.h"
#include "fd_redirect.h"
#include "pipe_buffer.h"
#include "snd_engine.h"

extern volatile u32 tick_count;
extern void kapi_sys_exit(int status);

void __cdecl wrap_gfx_init(void)
{
    gfx_init();
}

void __cdecl wrap_gfx_shutdown(void)
{
    gfx_shutdown();
}

void __cdecl wrap_gfx_present(void)
{
    gfx_present();
}

int __cdecl wrap_kbd_trygetchar(void)
{
    return kbd_trygetchar();
}

void * __cdecl wrap_mem_alloc(u32 size)
{
    return exec_heap_alloc(size);
}

void __cdecl wrap_mem_free(void *ptr)
{
    exec_heap_free(ptr);
}

u32 __cdecl wrap_get_tick(void)
{
    return tick_count;
}

int __cdecl wrap_sys_unlink(const char *path)
{
    return vfs_rm(path);
}

int __cdecl wrap_sys_rename(const char *oldpath, const char *newpath)
{
    return vfs_rename(oldpath, newpath);
}

int __cdecl wrap_sys_mkdir(const char *path)
{
    return vfs_mkdir(path);
}

int __cdecl wrap_sys_ls(const char *path, void *cb, void *ctx)
{
    return vfs_ls(path, (vfs_dir_cb)cb, ctx);
}

u32 __cdecl wrap_kmalloc_total(void)
{
    return kmalloc_total();
}

u32 __cdecl wrap_kmalloc_used(void)
{
    return kmalloc_used();
}

u32 __cdecl wrap_kmalloc_free(void)
{
    return kmalloc_free();
}

int __cdecl wrap_paging_enabled(void)
{
    return paging_enabled();
}

void __cdecl wrap_rtc_read(void *rtc_time)
{
    rtc_read((RTC_Time *)rtc_time);
}

void __cdecl wrap_tvram_clear(void)
{
    tvram_clear();
}

void __cdecl wrap_tvram_putchar_at(int x, int y, char ch, u8 attr)
{
    tvram_putchar_at(x, y, ch, attr);
}

void __cdecl wrap_tvram_putkanji_at(int x, int y, u16 jis, u8 attr)
{
    tvram_putkanji_at(x, y, jis, attr);
}

void __cdecl wrap_tvram_scroll(void)
{
    tvram_scroll();
}

int __cdecl wrap_kbd_getchar(void)
{
    return kbd_getchar();
}

int __cdecl wrap_kbd_getkey(void)
{
    return kbd_getkey();
}

int __cdecl wrap_kbd_trygetkey(void)
{
    return kbd_trygetkey();
}

int __cdecl wrap_sys_mount(const char *prefix, const char *dev, const char *fs)
{
    return vfs_mount(prefix, dev, fs);
}

void __cdecl wrap_sys_umount(const char *prefix)
{
    vfs_umount(prefix);
}

int __cdecl wrap_sys_is_mounted(const char *prefix)
{
    return vfs_is_mounted(prefix);
}

int __cdecl wrap_sys_chdir(const char *path)
{
    return vfs_chdir(path);
}

const char * __cdecl wrap_sys_getcwd(void)
{
    return vfs_cwd();
}

const char * __cdecl wrap_vfs_devname(const char *prefix)
{
    return vfs_devname(prefix);
}

int __cdecl wrap_vfs_sync(void)
{
    return vfs_sync();
}

int __cdecl wrap_sys_rmdir(const char *path)
{
    return vfs_rmdir(path);
}

void __cdecl wrap_serial_init(u32 baud)
{
    serial_init(baud);
}

void __cdecl wrap_serial_puts(const char *s)
{
    serial_puts(s);
}

int __cdecl wrap_serial_getchar(void)
{
    return serial_getchar();
}

void __cdecl wrap_serial_putchar(u8 ch)
{
    serial_putchar(ch);
}

int __cdecl wrap_serial_trygetchar(void)
{
    return serial_trygetchar();
}

int __cdecl wrap_serial_is_initialized(void)
{
    return serial_is_initialized();
}

int __cdecl wrap_exec_run(const char *path)
{
    return exec_run(path);
}

int __cdecl wrap_dev_count(void)
{
    return dev_count();
}

int __cdecl wrap_dev_get_info(int idx, char *name, int nm, int *type, u32 *sects)
{
    return dev_api_get_info(idx, name, nm, type, sects);
}

void __cdecl wrap_fm_startup_sound(void)
{
    fm_startup_sound();
}

void __cdecl wrap_fm_play_mml(const char *mml)
{
    fm_play_mml(mml);
}

int __cdecl wrap_np2_detect(void)
{
    return np2_detect();
}

void __cdecl wrap_np2_get_version(char *buf, int size)
{
    np2_get_version(buf, size);
}

void __cdecl wrap_np2_get_cpu(char *buf, int size)
{
    np2_get_cpu(buf, size);
}

void __cdecl wrap_np2_get_clock(char *buf, int size)
{
    np2_get_clock(buf, size);
}

int __cdecl wrap_np2_check_hostdrv(char *buf, int size)
{
    return np2_check_hostdrv(buf, size);
}

void __cdecl wrap_ide_init(void)
{
    ide_init();
}

int __cdecl wrap_ide_drive_present(int drv)
{
    return ide_drive_present(drv);
}

int __cdecl wrap_ide_identify(int drv, void *info)
{
    return ide_identify(drv, (IdeInfo *)info);
}

int __cdecl wrap_ide_read_sector(int drv, u32 lba, void *buf)
{
    return ide_read_sector(drv, lba, buf);
}

const char * __cdecl wrap_path_get_drive(void)
{
    return path_get_drive();
}

const char * __cdecl wrap_path_get_cwd(void)
{
    return path_get_cwd();
}

int __cdecl wrap_path_set_drive(const char *d)
{
    return path_set_drive(d);
}

void __cdecl wrap_path_set_cwd(const char *p)
{
    path_set_cwd(p);
}

void __cdecl wrap_path_parse(const char *input, void *result)
{
    path_parse(input, (ParsedPath *)result);
}

int __cdecl wrap_ext2_format(int drv, u32 sectors)
{
    return ext2_format(drv, sectors);
}

void __cdecl wrap_kcg_init(void)
{
    kcg_init();
}

void __cdecl wrap_kcg_set_scale(int s)
{
    kcg_set_scale(s);
}

void __cdecl wrap_buz_on(void)
{
    buz_on();
}

void __cdecl wrap_buz_off(void)
{
    buz_off();
}

void __cdecl wrap_rshell_set_active(int active)
{
    rshell_active = active;
}

int __cdecl wrap_ide_write_sector(int drv, u32 lba, const void *buf)
{
    return ide_write_sector(drv, lba, buf);
}

int __cdecl wrap_ide_write_sectors(int drv, u32 lba, u32 cnt, const void *buf)
{
    return ide_write_sectors(drv, lba, cnt, buf);
}

void __cdecl wrap_sys_reboot(void)
{
    sys_reboot();
}

void __cdecl wrap_sys_halt(void)
{
    sys_halt();
}

void __cdecl wrap_shell_putchar(char ch, u8 attr)
{
    shell_putchar(ch, attr);
}

void __cdecl wrap_shell_print_utf8(const char *utf8_str, u8 color)
{
    shell_print_utf8(utf8_str, color);
}

int __cdecl wrap_console_get_cursor_x(void)
{
    return console_get_cursor_x();
}

int __cdecl wrap_console_get_cursor_y(void)
{
    return console_get_cursor_y();
}

void __cdecl wrap_console_set_cursor(int x, int y)
{
    console_set_cursor(x, y);
}

int __cdecl wrap_sys_open(const char *path, int mode)
{
    return vfs_open(path, mode);
}

void __cdecl wrap_sys_close(int fd)
{
    vfs_close(fd);
}

int __cdecl wrap_sys_read(int fd, void *buf, u32 size)
{
    return vfs_read_fd(fd, buf, size);
}

int __cdecl wrap_sys_write(int fd, const void *buf, u32 size)
{
    return vfs_write_fd(fd, buf, size);
}

int __cdecl wrap_sys_lseek(int fd, int offset, int whence)
{
    return vfs_seek(fd, offset, whence);
}

void __cdecl wrap_console_get_size(int *w, int *h)
{
    console_get_size(w, h);
}

u32 __cdecl wrap_kbd_get_modifiers(void)
{
    return kbd_get_modifiers();
}

u32 __cdecl wrap_sys_get_mem_kb(void)
{
    return sys_get_mem_kb();
}

os_time_t __cdecl wrap_sys_time(void)
{
    return sys_time();
}

void __cdecl wrap_gfx_hardware_scroll(int lines)
{
    gfx_hardware_scroll(lines);
}

void __cdecl wrap_gfx_present_rect(int x, int y, int w, int h)
{
    gfx_present_rect(x, y, w, h);
}

void __cdecl wrap_sys_exit(int status)
{
    kapi_sys_exit(status);
}

int __cdecl wrap_sys_isatty(int fd)
{
    return vfs_isatty(fd);
}

int __cdecl wrap_sys_stat(const char *path, OS32_Stat *buf)
{
    return vfs_stat(path, buf);
}

int __cdecl wrap_sys_fstat(int fd, OS32_Stat *buf)
{
    return vfs_fstat(fd, buf);
}

void __cdecl wrap_gfx_set_palette(int idx, u8 r, u8 g, u8 b)
{
    palette_set(idx, r, g, b);
}

void __cdecl wrap_gfx_get_palette(int idx, u8 *r, u8 *g, u8 *b)
{
    palette_get(idx, r, g, b);
}

void __cdecl wrap_gfx_get_framebuffer(void *fb)
{
    gfx_get_framebuffer(fb);
}

void __cdecl wrap_gfx_add_dirty_rect(int x, int y, int w, int h)
{
    gfx_add_dirty_rect(x, y, w, h);
}

void __cdecl wrap_gfx_present_dirty(void)
{
    gfx_present_dirty();
}

void __cdecl wrap_gfx_present_raster(void *table)
{
    gfx_present_raster((GFX_RasterPalTable *)table);
}

void __cdecl wrap_kcg_read_ank(u8 ch, u8 *buf)
{
    kcg_read_ank(ch, buf);
}

void __cdecl wrap_kcg_read_kanji(u16 jis_code, u8 *buf)
{
    kcg_read_kanji(jis_code, buf);
}

void * __cdecl wrap_sys_shm_alloc(int blocks)
{
    return shm_alloc(blocks);
}

int __cdecl wrap_sys_shm_lock(void *ptr)
{
    return shm_lock(ptr);
}

int __cdecl wrap_sys_shm_free(void *ptr)
{
    return shm_free(ptr);
}

int __cdecl wrap_ime_getchar(void)
{
    return ime_getchar();
}

int __cdecl wrap_ime_trygetchar(void)
{
    return ime_trygetchar();
}

void __cdecl wrap_ime_toggle(void)
{
    ime_toggle();
}

int __cdecl wrap_ime_is_active(void)
{
    return ime_is_active();
}

void __cdecl wrap_ime_set_mode(int mode)
{
    ime_set_mode(mode);
}

int __cdecl wrap_ime_get_mode(void)
{
    return ime_get_mode();
}

int __cdecl wrap_ime_getkey(void)
{
    return ime_getkey();
}

int __cdecl wrap_sys_redirect_fd(int fd, const char *path, int mode)
{
    return fd_redirect_to_file(fd, path, mode);
}

void __cdecl wrap_sys_reset_redirect(int fd)
{
    fd_redirect_reset(fd);
}

int __cdecl wrap_sys_is_redirected(int fd)
{
    return fd_is_redirected(fd);
}

int __cdecl wrap_sys_pipe_alloc(void)
{
    return pipe_alloc();
}

void __cdecl wrap_sys_pipe_free(int id)
{
    pipe_free(id);
}

u8 * __cdecl wrap_sys_pipe_get_buf(int id)
{
    return pipe_get_buf(id);
}

u32 __cdecl wrap_sys_pipe_get_len(int id)
{
    return pipe_get_len(id);
}

void __cdecl wrap_sys_pipe_clear(int id)
{
    pipe_clear(id);
}

int __cdecl wrap_sys_redirect_fd_buf(int fd, u8 *buf, u32 size, u32 len)
{
    return fd_redirect_to_buffer(fd, buf, size, len);
}

u32 __cdecl wrap_sys_redirect_get_buf_len(int fd)
{
    return fd_redirect_get_buf_len(fd);
}

int __cdecl wrap_paging_is_present(u32 addr)
{
    return paging_is_present(addr);
}

void __cdecl wrap_snd_bgm_play(const char *mml)
{
    snd_bgm_play(mml);
}

void __cdecl wrap_snd_bgm_stop(void)
{
    snd_bgm_stop();
}

int __cdecl wrap_snd_bgm_is_playing(void)
{
    return snd_bgm_is_playing();
}

void __cdecl wrap_snd_se_play(int se_id)
{
    snd_se_play(se_id);
}

void __cdecl wrap_snd_se_play_raw(int note, int duration_ticks, int tone)
{
    snd_se_play_raw(note, duration_ticks, tone);
}

void __cdecl wrap_snd_set_master(int enable)
{
    snd_set_master(enable);
}

void __cdecl wrap_snd_bgm_set_persist(int persist)
{
    snd_bgm_set_persist(persist);
}

