import json
import re
import sys

with open("sdk/kapi.json", "r", encoding="utf-8") as f:
    data = json.load(f)

def get_arg_names(args):
    names = []
    for a in args:
        if a == "...":
            names.append("...")
            continue
        m = re.search(r'([a-zA-Z0-9_]+)(\[[0-9]*\])?$', a)
        if m:
            names.append(m.group(1))
        else:
            names.append(a)
    return names

# --- HEADER (os32_kapi_generated.h) ---
header_content = """/* AUTOGENERATED FILE - DO NOT EDIT */
#ifndef OS32_KAPI_GENERATED_H
#define OS32_KAPI_GENERATED_H

typedef struct {
    u32 magic;
    u32 version;
"""
for api in data["api"]:
    ret = api["ret"]
    name = api["name"]
    args = ", ".join(api["args"]) if api.get("args") else "void"
    header_content += f"    {ret} (__cdecl *{name})({args});\n"

# データフィールド (関数ポインタではない u32 等のフィールド)
for field in data.get("data_fields", []):
    comment = field.get("comment", "")
    if comment:
        header_content += f"    {field['type']} {field['name']};  /* {comment} */\n"
    else:
        header_content += f"    {field['type']} {field['name']};\n"

header_content += "} KernelAPI;\n\n"

# --- M2 (KAPI トランポリン): CONTRACTS C5 ---
# KAPI_FUNC_COUNT = 関数スロット数 (トランポリンのスタブ生成ループ / int 0x80
# ディスパッチャの範囲チェックに使う)。データフィールドは含めない。
header_content += f"#define KAPI_FUNC_COUNT {len(data['api'])}\n"
# kapi_argsize[slot] = 各スロットの cdecl 引数バイト数 (固定分)。i386 では
# int/ポインタ/char/short いずれも 4B スタックスロット。可変長 (...) は
# 固定分のみを数える (ディスパッチャが下限に使う)。カーネル側 (kapi_generated.c)
# で定義。プログラム側では未使用。
header_content += "extern const u16 kapi_argsize[KAPI_FUNC_COUNT];\n"

header_content += "\n#endif\n"

with open("sdk/include/os32/os32_kapi_generated.h", "w", encoding="utf-8") as f:
    f.write(header_content)


# --- C FILE (kapi_generated.c) ---
c_content = "/* AUTOGENERATED FILE - DO NOT EDIT */\n#include \"os32_kapi_shared.h\"\n"
for inc in data.get("includes", []):
    c_content += f"#include \"{inc}\"\n"

c_content += "\n"
for ext in data.get("externs", []):
    c_content += f"{ext}\n"
c_content += "\n"

# 計測ビルド (-DKAPI_PROFILE) 用のカウンタ。既定では KAPI_HIT が空になる。
# slot 番号は api 配列の並び順 = KernelAPI 表の並び順 (exec_kapi_init.inc と同じ)。
c_content += '#include "kapi_profile.h"\n\n'
c_content += "#ifdef KAPI_PROFILE\n"
c_content += f"volatile u32 kapi_hits[{len(data['api'])}];\n"
c_content += "#endif\n\n"

# --- M2: kapi_argsize[] (CONTRACTS C5) ---
# slot = api 配列の並び順 (KernelAPI 表 / wrap / init と同一)。
c_content += "/* 各スロットの cdecl 引数バイト数 (固定分)。int 0x80 ディスパッチャが\n"
c_content += " * ユーザスタックからこの量をコピーして本物の wrap を呼ぶ (可変長は下限)。 */\n"
c_content += "const u16 kapi_argsize[KAPI_FUNC_COUNT] = {\n"
for _slot, _api in enumerate(data["api"]):
    _fixed = [a for a in _api.get("args", []) if a != "..."]
    _bytes = 4 * len(_fixed)
    _variadic = any(a == "..." for a in _api.get("args", []))
    _tag = "  /* %s%s */" % (_api["name"], " (...)" if _variadic else "")
    c_content += f"    {_bytes},{_tag}\n"
c_content += "};\n\n"

for slot, api in enumerate(data["api"]):
    if api.get("direct", False):
        continue
        
    ret = api["ret"]
    name = api["name"]
    args_str = ", ".join(api.get("args", []))
    if not args_str: args_str = "void"
    
    c_content += f"{ret} __cdecl wrap_{name}({args_str})\n{{\n"
    c_content += f"    KAPI_HIT({slot});\n"
    
    if "body" in api:
        lines = api["body"].split("\n")
        for line in lines:
            c_content += f"    {line}\n"
    else:
        target = api.get("target", name)
        arg_names = get_arg_names(api.get("args", []))
        args_call = ", ".join(arg_names)
        
        if ret == "void":
            c_content += f"    {target}({args_call});\n"
        else:
            c_content += f"    return {target}({args_call});\n"
            
    c_content += "}\n\n"

with open("kapi/kapi_generated.c", "w", encoding="utf-8") as f:
    f.write(c_content)

# --- INC FILE (exec_kapi_init.inc) ---
inc_content = "/* AUTOGENERATED FILE - DO NOT EDIT */\n"

for api in data["api"]:
    if not api.get("direct", False):
        ret = api["ret"]
        name = api["name"]
        args_str = ", ".join(api.get("args", []))
        if not args_str: args_str = "void"
        inc_content += f"extern {ret} __cdecl wrap_{name}({args_str});\n"

inc_content += "\nkapi->magic = 0x4B415049UL;\n"
inc_content += f"kapi->version = {data['version']};\n\n"

for api in data["api"]:
    name = api["name"]
    if api.get("direct", False):
        target = api.get("target", name)
        inc_content += f"    kapi->{name} = (void *){target};\n"
    else:
        inc_content += f"    kapi->{name} = wrap_{name};\n"

# データフィールド初期化 (デフォルトは0、exec_run等で動的にセットされる)
for field in data.get("data_fields", []):
    inc_content += f"    kapi->{field['name']} = 0;\n"

with open("exec/exec_kapi_init.inc", "w", encoding="utf-8") as f:
    f.write(inc_content)
    
print("SSOT: Successfully generated kapi files.")
