import json
import re
import sys

with open("tools/kapi.json", "r", encoding="utf-8") as f:
    data = json.load(f)

def get_arg_names(args):
    names = []
    for a in args:
        if a == "...":
            names.append("...")
            continue
        m = re.search(r'([a-zA-Z0-9_]+)(\[[0-9]*\])?$', a)
        if m:
            names.append(m.group(1))
        else:
            names.append(a)
    return names

# --- HEADER (os32_kapi_generated.h) ---
header_content = """/* AUTOGENERATED FILE - DO NOT EDIT */
#ifndef OS32_KAPI_GENERATED_H
#define OS32_KAPI_GENERATED_H

typedef struct {
    u32 magic;
    u32 version;
"""
for api in data["api"]:
    ret = api["ret"]
    name = api["name"]
    args = ", ".join(api["args"]) if api.get("args") else "void"
    header_content += f"    {ret} (__cdecl *{name})({args});\n"

# データフィールド (関数ポインタではない u32 等のフィールド)
for field in data.get("data_fields", []):
    comment = field.get("comment", "")
    if comment:
        header_content += f"    {field['type']} {field['name']};  /* {comment} */\n"
    else:
        header_content += f"    {field['type']} {field['name']};\n"

header_content += "} KernelAPI;\n\n#endif\n"

with open("include/os32_kapi_generated.h", "w", encoding="utf-8") as f:
    f.write(header_content)


# --- C FILE (kapi_generated.c) ---
c_content = "/* AUTOGENERATED FILE - DO NOT EDIT */\n#include \"os32_kapi_shared.h\"\n"
for inc in data.get("includes", []):
    c_content += f"#include \"{inc}\"\n"

c_content += "\n"
for ext in data.get("externs", []):
    c_content += f"{ext}\n"
c_content += "\n"

for api in data["api"]:
    if api.get("direct", False):
        continue
        
    ret = api["ret"]
    name = api["name"]
    args_str = ", ".join(api.get("args", []))
    if not args_str: args_str = "void"
    
    c_content += f"{ret} __cdecl wrap_{name}({args_str})\n{{\n"
    
    if "body" in api:
        lines = api["body"].split("\n")
        for line in lines:
            c_content += f"    {line}\n"
    else:
        target = api.get("target", name)
        arg_names = get_arg_names(api.get("args", []))
        args_call = ", ".join(arg_names)
        
        if ret == "void":
            c_content += f"    {target}({args_call});\n"
        else:
            c_content += f"    return {target}({args_call});\n"
            
    c_content += "}\n\n"

with open("kapi/kapi_generated.c", "w", encoding="utf-8") as f:
    f.write(c_content)

# --- INC FILE (exec_kapi_init.inc) ---
inc_content = "/* AUTOGENERATED FILE - DO NOT EDIT */\n"

for api in data["api"]:
    if not api.get("direct", False):
        ret = api["ret"]
        name = api["name"]
        args_str = ", ".join(api.get("args", []))
        if not args_str: args_str = "void"
        inc_content += f"extern {ret} __cdecl wrap_{name}({args_str});\n"

inc_content += "\nkapi->magic = 0x4B415049UL;\n"
inc_content += f"kapi->version = {data['version']};\n\n"

for api in data["api"]:
    name = api["name"]
    if api.get("direct", False):
        target = api.get("target", name)
        inc_content += f"    kapi->{name} = (void *){target};\n"
    else:
        inc_content += f"    kapi->{name} = wrap_{name};\n"

# データフィールド初期化 (デフォルトは0、exec_run等で動的にセットされる)
for field in data.get("data_fields", []):
    inc_content += f"    kapi->{field['name']} = 0;\n"

with open("exec/exec_kapi_init.inc", "w", encoding="utf-8") as f:
    f.write(inc_content)
    
print("SSOT: Successfully generated kapi files.")
